9oormthon-univ/2024_DANPOONG_TEAM_43_BE

src/main/java/com/carely/backend/BackendApplication.java, src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/config/WebConfig.java, src/main/java/com/carely/backend/domain/common/BaseEntity.java, src/main/java/com/carely/backend/dto/response/ErrorResponseDTO.java, src/main/java/com/carely/backend/dto/response/ResponseDTO.java, src/main/java/com/carely/backend/exception/DuplicateUsernameException.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java
=> ⚙️ [CHORE] 프로젝트 초기 설정 

build.gradle, src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/config/SecurityConfig.java, src/main/java/com/carely/backend/controller/UserController.java, src/main/java/com/carely/backend/domain/RefreshEntity.java, src/main/java/com/carely/backend/domain/User.java, src/main/java/com/carely/backend/domain/enums/Role.java, src/main/java/com/carely/backend/domain/enums/UserType.java, src/main/java/com/carely/backend/domain/enums/VolunteerType.java, src/main/java/com/carely/backend/dto/user/CustomUserDetails.java, src/main/java/com/carely/backend/dto/user/MyPageDTO.java, src/main/java/com/carely/backend/dto/user/NotUserDTO.java, src/main/java/com/carely/backend/dto/user/RegisterDTO.java, src/main/java/com/carely/backend/dto/user/UserResponseDTO.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/exception/KakaoException.java, src/main/java/com/carely/backend/jwt/JWTFilter.java, src/main/java/com/carely/backend/jwt/JWTUtil.java, src/main/java/com/carely/backend/jwt/LoginFilter.java, src/main/java/com/carely/backend/repository/RefreshRepository.java, src/main/java/com/carely/backend/repository/UserRepository.java, src/main/java/com/carely/backend/service/UserService.java, src/main/java/com/carely/backend/service/kakao/KakaoAddressService.java, src/main/java/com/carely/backend/service/kakao/KakaoLoginService.java, src/main/java/com/carely/backend/service/parser/AddressParser.java, src/main/java/com/carely/backend/service/s3/MultipartJackson2HttpMessageConverter.java, src/main/java/com/carely/backend/util/TokenErrorResponse.java
- 회원가입, 카카오 로그인
- 회원가입, 카카오 로그인
Resolved #1
=> ✨ [FEAT] 회원가입, 카카오 로그인

src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/config/SwaggerConfig.java, src/main/java/com/carely/backend/controller/UserController.java, src/main/java/com/carely/backend/controller/docs/UserAPI.java, src/main/java/com/carely/backend/jwt/CustomLogoutFilter.java
-  로그아웃 로직 구현 
-  로그아웃 로직 구현 
Resolved #1
=> ✨ [FEAT] 로그아웃 로직 구현 

src/main/java/com/carely/backend/config/SwaggerConfig.java, src/main/java/com/carely/backend/controller/UserController.java, src/main/java/com/carely/backend/controller/docs/UserAPI.java
=> 📝 [DOCS] Swagger 세팅

src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/config/SecurityConfig.java, src/main/java/com/carely/backend/controller/MapController.java, src/main/java/com/carely/backend/controller/UserController.java, src/main/java/com/carely/backend/controller/docs/MapAPI.java, src/main/java/com/carely/backend/controller/docs/UserAPI.java, src/main/java/com/carely/backend/domain/User.java, src/main/java/com/carely/backend/dto/user/AddressDTO.java, src/main/java/com/carely/backend/dto/user/MapUserDTO.java, src/main/java/com/carely/backend/jwt/LoginFilter.java, src/main/java/com/carely/backend/repository/UserRepository.java, src/main/java/com/carely/backend/service/UserService.java
- 위치 인증 및 조회
- 위치 인증 및 조회
Resolved #8
=> ✨ [FEAT] 위치 인증 및 조회

build.gradle, src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/config/RedisConfig.java, src/main/java/com/carely/backend/config/S3Config.java, src/main/java/com/carely/backend/config/WebSocketConfig.java, src/main/java/com/carely/backend/controller/ChatController.java, src/main/java/com/carely/backend/controller/docs/ChatAPI.java, src/main/java/com/carely/backend/domain/ChatMessageEntity.java, src/main/java/com/carely/backend/domain/ChatRoomCountEntity.java, src/main/java/com/carely/backend/domain/ChatRoomEntity.java, src/main/java/com/carely/backend/dto/chat/ChatRequest.java, src/main/java/com/carely/backend/dto/chat/ChatRoomDTO.java, src/main/java/com/carely/backend/dto/chat/ChatRoomResponseDTO.java, src/main/java/com/carely/backend/dto/user/UserResponseDTO.java, src/main/java/com/carely/backend/repository/ChatMessageRepository.java, src/main/java/com/carely/backend/repository/ChatRoomCountRepository.java, src/main/java/com/carely/backend/repository/ChatRoomRepository.java, src/main/java/com/carely/backend/service/UserService.java, src/main/java/com/carely/backend/service/chat/ChatService.java, src/main/java/com/carely/backend/service/chat/SessionManager.java, src/main/java/com/carely/backend/service/s3/S3Uploader.java
- 웹소켓, 채팅 구현
- 웹소켓, 채팅 구현
Resolved #10
=> ✨ [FEAT] 웹소켓, 채팅 구현

src/main/java/com/carely/backend/controller/MapController.java, src/main/java/com/carely/backend/domain/enums/UserType.java, src/main/java/com/carely/backend/dto/user/MapUserDTO.java, src/main/java/com/carely/backend/service/UserService.java
- 지도 관련 응답 수정
- 지도 관련 응답 수정
Resolved #13
=> 🐛 [FIX] 지도 관련 응답 수정

src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/controller/VolunteerController.java, src/main/java/com/carely/backend/controller/docs/VolunteerAPI.java, src/main/java/com/carely/backend/domain/Volunteer.java, src/main/java/com/carely/backend/dto/user/MapUserDTO.java, src/main/java/com/carely/backend/dto/user/MyPageDTO.java, src/main/java/com/carely/backend/dto/volunteer/CreateVolunteerDTO.java, src/main/java/com/carely/backend/dto/volunteer/GetVolunteerInfoDTO.java, src/main/java/com/carely/backend/dto/volunteer/UpdateVolunteerApprovalDTO.java, src/main/java/com/carely/backend/exception/ChatMessageNotFoundException.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/exception/UserNotFoundException.java, src/main/java/com/carely/backend/exception/VolunteerNotFoundException.java, src/main/java/com/carely/backend/repository/VolunteerRepository.java, src/main/java/com/carely/backend/service/UserService.java, src/main/java/com/carely/backend/service/VolunteerService.java
- 봉사 요청하기, 승인하기 구현
- 봉사 요청하기, 승인하기 구현
Resolved #11
=> ✨ [FEAT] 봉사 요청하기, 승인하기 구현

src/main/java/com/carely/backend/controller/MapController.java, src/main/java/com/carely/backend/service/UserService.java
- userType 확인 service단으로 수정
- userType 확인 service단으로 수정
Resolved #16
=> ♻️ [REFACTOR] userType 확인 service단으로 수정

src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/exception/NotValidAddressException.java, src/main/java/com/carely/backend/service/parser/AddressParser.java
- 유효한 주소가 아닐 경우 예외 처리 
- 유효한 주소가 아닐 경우 예외 처리 
Resolved #18
=> 🥅 [FIX] 유효한 주소가 아닐 경우 예외 처리 

src/main/java/com/carely/backend/dto/user/MapUserDTO.java, src/main/java/com/carely/backend/service/UserService.java, src/main/java/com/carely/backend/service/kakao/KakaoAddressService.java
- 지도에서 유저 조회 시 km 리턴 
- 지도에서 유저 조회 시 km 리턴 
Resolved #20
=> ✨ [FEAT] 지도에서 유저 조회 시 km 리턴 

.github/workflows/deploy.yml, Dockerfile
=> 🚀 [DEPLOY] 배포

src/main/java/com/carely/backend/controller/MapController.java, src/main/java/com/carely/backend/controller/docs/MapAPI.java, src/main/java/com/carely/backend/dto/user/MapUserDTO.java, src/main/java/com/carely/backend/repository/UserRepository.java, src/main/java/com/carely/backend/service/UserService.java
=> 🐛 [FIX] 지도에서 유저 전체 리턴 

src/main/java/com/carely/backend/config/SwaggerConfig.java
=> 🐛 [FIX] Deploy Server URL Swagger 추가

src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/controller/UserController.java, src/main/java/com/carely/backend/dto/user/RecommandUserDTO.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/exception/KakaoIdNotFoundException.java, src/main/java/com/carely/backend/exception/UserMustCaregiverException.java, src/main/java/com/carely/backend/exception/UserMustNotCaregiverException.java, src/main/java/com/carely/backend/repository/UserRepository.java, src/main/java/com/carely/backend/service/UserService.java, src/main/java/com/carely/backend/service/VolunteerService.java
=> ✨ [FEAT] 유저 추천

build.gradle, src/main/java/com/carely/backend/config/SecurityConfig.java
- Cors 설정에 백엔드 배포 도메인 추가 
- Cors 설정에 백엔드 배포 도메인 추가 
Resolved #이슈번호
=> 🐛 [FIX] Cors 설정에 백엔드 배포 도메인 추가 

src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/controller/UserController.java, src/main/java/com/carely/backend/controller/docs/UserAPI.java, src/main/java/com/carely/backend/service/UserService.java
=> ✨ [FEAT] 유저 삭제 API 작성

src/main/java/com/carely/backend/domain/User.java, src/main/java/com/carely/backend/domain/Volunteer.java
=> 🐛 [FIX] nullable 삭제 

src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/config/OpenAIConfig.java, src/main/java/com/carely/backend/controller/MemoController.java, src/main/java/com/carely/backend/controller/docs/MemoAPI.java, src/main/java/com/carely/backend/domain/GuestBookEntity.java, src/main/java/com/carely/backend/domain/Memo.java, src/main/java/com/carely/backend/domain/Volunteer.java, src/main/java/com/carely/backend/dto/memo/CreateMemoDTO.java, src/main/java/com/carely/backend/dto/memo/MemoResponseDTO.java, src/main/java/com/carely/backend/dto/openai/CompletionRequestDTO.java, src/main/java/com/carely/backend/dto/openai/CompletionResponseDTO.java, src/main/java/com/carely/backend/dto/volunteer/GetVolunteerInfoDTO.java, src/main/java/com/carely/backend/exception/AlreadyExistsMemoException.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/repository/MemoRepository.java, src/main/java/com/carely/backend/repository/VolunteerRepository.java, src/main/java/com/carely/backend/service/MemoService.java, src/main/java/com/carely/backend/service/OpenAIService.java
=> ✨ [FEAT] Memo 관련 API 구현 

src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/controller/VolunteerController.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/exception/NotEligibleCaregiver.java, src/main/java/com/carely/backend/service/VolunteerService.java
=> 🥅 [FEAT] 약속 요청을 받은 대상자가 아니라면 예외 발생 

src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/controller/VolunteerController.java, src/main/java/com/carely/backend/exception/AlreadyApprovedException.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/exception/NotMatchChatroomException.java, src/main/java/com/carely/backend/service/VolunteerService.java
=> 🐛 [FIX] 채팅방 id 일치 여부, 이미 승인되었는지 여부 확인 

src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/controller/GuestBookController.java, src/main/java/com/carely/backend/controller/docs/GuestBookAPI.java, src/main/java/com/carely/backend/domain/Volunteer.java, src/main/java/com/carely/backend/repository/GuestBookRepository.java, src/main/java/com/carely/backend/service/GuestBookService.java
- 🔀 [MERGE] 브랜치 머지
- 🔀 [MERGE] 브랜치 머지
Resolved #25
=> 🔀 [MERGE] 브랜치 머지

build.gradle, src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/config/GoogleVisionConfig.java, src/main/java/com/carely/backend/controller/GuestBookController.java, src/main/java/com/carely/backend/controller/OCRController.java, src/main/java/com/carely/backend/controller/docs/GuestBookAPI.java, src/main/java/com/carely/backend/controller/docs/OcrAPI.java, src/main/java/com/carely/backend/domain/User.java, src/main/java/com/carely/backend/domain/Volunteer.java, src/main/java/com/carely/backend/dto/ocr/OCRResponseDto.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/exception/UserNotMatchException.java, src/main/java/com/carely/backend/service/ocr/OCRService.java
- ✨ [FEAT] 회원정보와 자격증 정보가 일치하지 않을 때 구현, ocr 검출 기능 구현
- ✨ [FEAT] 회원정보와 자격증 정보가 일치하지 않을 때 구현, ocr 검출 기능 구현
Resolved #46
=> ✨ [FEAT] 회원정보와 자격증 정보가 일치하지 않을 때 구현, ocr 검출 기능 구현

src/main/java/com/carely/backend/dto/guestBook/ResponseGuestBookDTO.java
- ✨ [FEAT] 유저 타입 추가
- ✨ [FEAT] 유저 타입 추가
Resolved #25
=> ✨ [FEAT] 유저 타입 추가

src/main/java/com/carely/backend/dto/guestBook/ResponseGuestBookDTO.java, src/main/java/com/carely/backend/service/GuestBookService.java
- 🐛 [FIX] dto 수정
- 🐛 [FIX] dto 수정
Resolved #이슈번호
=> 🐛 [FIX] dto 수정

src/main/java/com/carely/backend/service/GuestBookService.java
-✨ [FEAT] 방명록 안 적어준 건 제외
- ✨ [FEAT] 방명록 안 적어준 건 제외
Resolved #이슈번호
=> ✨ [FEAT] 방명록 안 적어준 건 제외

src/main/java/com/carely/backend/dto/guestBook/ResponseGuestBookDTO.java, src/main/java/com/carely/backend/service/GuestBookService.java
- ✨ [FEAT] 유저 id 전달
- ✨ [FEAT] 유저 id 전달
Resolved #이슈번호
=> ✨ [FEAT] 유저 id 전달

src/main/java/com/carely/backend/dto/user/RecommandUserDTO.java
=> ✨ [FEAT] 유저 추천 시 능력 전달 

src/main/java/com/carely/backend/domain/User.java
=> 🐛 [FIX] User엔터티로 변경

src/main/java/com/carely/backend/controller/OCRController.java, src/main/java/com/carely/backend/controller/docs/OcrAPI.java, src/main/java/com/carely/backend/dto/ocr/OCRCreateDTO.java
=> 🐛 [FIX] username 받도록 수정

src/main/java/com/carely/backend/controller/OCRController.java
=> 🐛 [FIX] json 추가 #59

src/main/java/com/carely/backend/controller/OCRController.java
=> 🐛 [FIX] requestPart로 수정 #59

src/main/java/com/carely/backend/controller/OCRController.java
=> 🐛 [FIX] media type 에러 해결 #59

src/main/java/com/carely/backend/controller/OCRController.java
=> 🎨 [STYLE] 메서드명 변경 #59

src/main/java/com/carely/backend/service/ocr/OCRService.java
=> 🐛 [FIX] ocr 해결 #59

src/main/java/com/carely/backend/service/ocr/OCRService.java
=> 🐛 [FIX] ocr 정규식 패턴 수정 #59

src/main/java/com/carely/backend/domain/Memo.java, src/main/java/com/carely/backend/domain/Volunteer.java, src/main/java/com/carely/backend/domain/common/BaseEntity.java, src/main/java/com/carely/backend/dto/volunteer/GetVolunteerInfoDTO.java, src/main/java/com/carely/backend/service/MemoService.java, src/main/java/com/carely/backend/service/VolunteerService.java
=> 🐛 [FIX] memo 대상자 전달 #68

src/main/java/com/carely/backend/domain/Memo.java, src/main/java/com/carely/backend/domain/User.java, src/main/java/com/carely/backend/domain/Volunteer.java, src/main/java/com/carely/backend/service/MemoService.java
=> 🐛 [FIX] 메모 출력 로직 수정 #68

src/main/java/com/carely/backend/config/SecurityConfig.java, src/main/java/com/carely/backend/controller/VolunteerController.java
=> 🐛 [FIX] PATCH 허용 #72

src/main/java/com/carely/backend/dto/group/GetGroupDTO.java
=> ✨ [FEAT] 모임 상세 조회 시 type 함께 응답 #74

src/main/java/com/carely/backend/service/MemoService.java, src/main/java/com/carely/backend/service/OpenAIService.java
=> 🐛 [FIX] voiding null로 저장되는 문제 해결 #76

src/main/java/com/carely/backend/config/SecurityConfig.java
=> 🐛 [FIX] 배포 서버 반영

src/main/java/com/carely/backend/config/SecurityConfig.java, src/main/java/com/carely/backend/controller/UserController.java, src/main/java/com/carely/backend/service/kakao/KakaoLoginService.java
=> redirect url

src/main/java/com/carely/backend/service/kakao/KakaoLoginService.java
=> local server

src/main/java/com/carely/backend/domain/User.java, src/main/java/com/carely/backend/dto/user/MapUserDTO.java, src/main/java/com/carely/backend/dto/user/RecommandUserDTO.java, src/main/java/com/carely/backend/dto/user/RegisterDTO.java, src/main/java/com/carely/backend/service/UserService.java, src/main/java/com/carely/backend/service/ocr/OCRService.java
=> ♻️ [REFACTOR] 응답 속도를 높이기 위한 latitude, longtitude 필드 생성 

src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/controller/GroupController.java, src/main/java/com/carely/backend/controller/NewsController.java, src/main/java/com/carely/backend/controller/docs/NewsAPI.java, src/main/java/com/carely/backend/domain/Group.java, src/main/java/com/carely/backend/domain/News.java, src/main/java/com/carely/backend/domain/NewsComment.java, src/main/java/com/carely/backend/dto/group/CreateGroupDTO.java, src/main/java/com/carely/backend/dto/group/GetGroupDTO.java, src/main/java/com/carely/backend/dto/news/NewsCommentResponseDTO.java, src/main/java/com/carely/backend/dto/news/NewsResponseDTO.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/exception/NewsNotFoundException.java, src/main/java/com/carely/backend/repository/NewsCommentRepository.java, src/main/java/com/carely/backend/repository/NewsRepository.java, src/main/java/com/carely/backend/service/GroupService.java, src/main/java/com/carely/backend/service/LikeService.java, src/main/java/com/carely/backend/service/NewsService.java
=> ✨ [FEAT] 그룹 소식 및 댓글 구현 

src/main/java/com/carely/backend/controller/OCRController.java, src/main/java/com/carely/backend/service/UserService.java, src/main/java/com/carely/backend/service/VolunteerService.java, src/main/java/com/carely/backend/service/ocr/OCRService.java
- ✨ [FEAT] OCR 기능 적용 완료
- ✨ [FEAT] OCR 기능 적용 완료
Resolved #89
=> ✨ [FEAT] OCR 기능 적용 완료

src/main/java/com/carely/backend/controller/CertificateController.java
- 📝 [MEMO] 주석 추가
- 📝 [MEMO] 주석 추가
Resolved #이슈번호
=> 📝 [MEMO] 주석 추가

src/main/java/com/carely/backend/controller/CertificateController.java, src/main/java/com/carely/backend/controller/DocumentIssuedController.java, src/main/java/com/carely/backend/controller/UserController.java, src/main/java/com/carely/backend/service/DocumentIssuedService.java, src/main/java/com/carely/backend/service/VolunteerService.java, src/main/java/com/carely/backend/service/kakao/KakaoLoginService.java
=> ✨ [FEAT] 본명을 가져올 수 있도록 수정

src/main/java/com/carely/backend/controller/UserController.java
=> ✨ [FEAT] 본명이 담길 수 있도록 수정

src/main/java/com/carely/backend/service/kakao/KakaoLoginService.java
=> ✨ [FEAT] 이름이 존재하지 않을 때 닉네임으로 정보 구현

src/main/java/com/carely/backend/service/certificate/CertificateService.java
=> ✨ [FEAT] OCR 검증 이름 동일한데 검증 안 되는 것 수정

src/main/java/com/carely/backend/service/VolunteerService.java
=> 🔇 [LOG] remove log

.github/workflows/deploy.yml
=> 🚀 [DEPLOY] 배포 문서 수정 외부 네트워크

src/main/java/com/carely/backend/service/certificate/CertificateService.java
=> 🔇 [LOGS] remove log

src/main/java/com/carely/backend/config/SecurityConfig.java
=> ✨ [FEAT] 블록체인 서버에서 접속할 수 있도록

src/main/java/com/carely/backend/config/SecurityConfig.java
=> 🔊 [LOGS] 로그 추가

src/main/java/com/carely/backend/config/Web3jConfig.java
=> 🔊 [LOGS] 추가

src/main/java/com/carely/backend/config/Web3jConfig.java, src/main/java/com/carely/backend/service/certificate/CertificateService.java
-♻️ [REFACTOR] ganache 주소 yml 에 추가
- 내용
Resolved #이슈번호
=> ♻️ [REFACTOR] ganache 주소 yml 에 추가

src/main/java/com/carely/backend/controller/UserController.java, src/main/java/com/carely/backend/controller/docs/UserAPI.java, src/main/java/com/carely/backend/domain/User.java, src/main/java/com/carely/backend/dto/user/NotUserDTO.java, src/main/java/com/carely/backend/dto/user/RegisterDTO.java, src/main/java/com/carely/backend/service/UserService.java, src/main/java/com/carely/backend/service/kakao/KakaoLoginService.java
- [✨ [FEAT] 유저 회원가입시 생년월일 성별 가져오기 구현](https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_43_BE/commit/83f0868595ae73668d2e1404a3428ae26642b3b8)
- ✨ [FEAT] 유저 회원가입시 생년월일 성별 전화번호 가져오기 구현
Resolved #108 아직 안 끝남...
=> ✨ [FEAT] 유저 회원가입시 생년월일 성별 전화번호 가져오기 구현

src/main/java/com/carely/backend/service/kakao/KakaoLoginService.java, src/main/java/com/carely/backend/service/ocr/OCRService.java
=> 🐛 [FIX] 키워드 인식 수정

src/main/java/com/carely/backend/controller/OCRController.java, src/main/java/com/carely/backend/controller/docs/OcrAPI.java, src/main/java/com/carely/backend/dto/ocr/OCRCreateDTO.java, src/main/java/com/carely/backend/service/ocr/OCRService.java
=> 🔥 [REMOVE] 검증 코드 삭제

src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/controller/NewsController.java, src/main/java/com/carely/backend/dto/news/CreateCommentDTO.java, src/main/java/com/carely/backend/dto/news/CreateNewsDTO.java, src/main/java/com/carely/backend/service/NewsService.java
=> ✨ [FEAT] 소식, 댓글 생성 API 작성 

src/main/java/com/carely/backend/controller/NewsController.java, src/main/java/com/carely/backend/service/NewsService.java
=> 🐛 [FIX] 소식 생성 시 groupId 전달 #

src/main/java/com/carely/backend/dto/news/NewsResponseDTO.java, src/main/java/com/carely/backend/repository/NewsRepository.java, src/main/java/com/carely/backend/service/NewsService.java
=> ✨ [FEAT] 소식, 댓글 조회 역순으로 응답 

src/main/java/com/carely/backend/controller/docs/NewsAPI.java, src/main/java/com/carely/backend/dto/news/CreateCommentDTO.java, src/main/java/com/carely/backend/dto/news/CreateNewsDTO.java
=> 📝 [DOCS] swagger 명세

src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/code/SuccessCode.java, src/main/java/com/carely/backend/controller/EasyCodefController.java, src/main/java/com/carely/backend/controller/docs/EasyCodefAPI.java, src/main/java/com/carely/backend/dto/document/ResponseDocumentDTO.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/exception/IdentityNotAcceptableException.java, src/main/java/com/carely/backend/service/DocumentIssuedService.java, src/main/java/com/carely/backend/service/EasyCodef/EasyCodefResponse.java
- [✨ [FEAT] swagger 추가 및 인증 로직 스케줄러 구현](https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_43_BE/commit/f7e97a734eea2a6c60dbb2bed8d189044d363c19)용
- [✨ [FEAT] swagger 추가 및 인증 로직 스케줄러 구현](https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_43_BE/commit/f7e97a734eea2a6c60dbb2bed8d189044d363c19)
Resolved #이슈번호
=> ✨ [FEAT] swagger 추가 및 인증 로직 스케줄러 구현

src/main/java/com/carely/backend/controller/DocumentIssuedController.java, src/main/java/com/carely/backend/controller/docs/DocumentAPI.java, src/main/java/com/carely/backend/controller/docs/EasyCodefAPI.java, src/main/java/com/carely/backend/service/DocumentIssuedService.java, src/main/java/com/carely/backend/service/certificate/CertificateService.java
- ✨ [FEAT] 봉사활동 확인서 추가
- ✨ [FEAT] 봉사활동 확인서 추가
Resolved #108
=> ✨ [FEAT] 봉사활동 확인서 추가

src/main/java/com/carely/backend/code/ErrorCode.java, src/main/java/com/carely/backend/controller/GroupController.java, src/main/java/com/carely/backend/controller/GuestBookController.java, src/main/java/com/carely/backend/controller/docs/GuestBookAPI.java, src/main/java/com/carely/backend/domain/Group.java, src/main/java/com/carely/backend/domain/GuestBookEntity.java, src/main/java/com/carely/backend/domain/Volunteer.java, src/main/java/com/carely/backend/dto/guestBook/ResponseGroupGuestbookDTO.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/exception/GuestBookNotFoundException.java, src/main/java/com/carely/backend/repository/GroupRepository.java, src/main/java/com/carely/backend/repository/GuestBookRepository.java, src/main/java/com/carely/backend/repository/JoinGroupRepository.java, src/main/java/com/carely/backend/repository/VolunteerRepository.java, src/main/java/com/carely/backend/service/GroupService.java, src/main/java/com/carely/backend/service/GuestBookService.java, src/main/java/com/carely/backend/service/VolunteerService.java
- ✨ [FEAT] 그룹별 방명록 불러오기
- ✨ [FEAT] 그룹별 방명록 불러오기
Resolved #이슈번호
=> ✨ [FEAT] 그룹별 방명록 불러오기

src/main/java/com/carely/backend/dto/user/MyPageDTO.java, src/main/java/com/carely/backend/dto/user/RegisterDTO.java, src/main/java/com/carely/backend/service/UserService.java
=> ✨ [FEAT] 나이 제외

src/main/java/com/carely/backend/service/UserService.java, src/main/java/com/carely/backend/service/ocr/OCRService.java
=> 🐛 [FIX] 회원가입 이전에 유저 찾는 로직 제외

src/main/java/com/carely/backend/service/ocr/OCRService.java
=> 🐛 [FIX] 으이그 ;;; final 도 없이 뭘하겠다고

src/main/java/com/carely/backend/controller/UserController.java
=> ✨ [FEAT] 프론트 사용할 개발용 유저 삭제

src/main/java/com/carely/backend/controller/docs/UserAPI.java
=> ✨ [FEAT] 유저 삭제

src/main/java/com/carely/backend/config/SecurityConfig.java
=> 🩹 [FIX] 보안에 삭제 url 추가

src/main/java/com/carely/backend/dto/user/MyPageDTO.java, src/main/java/com/carely/backend/dto/user/RegisterDTO.java, src/main/java/com/carely/backend/dto/user/UserResponseDTO.java, src/main/java/com/carely/backend/service/UserService.java
=> ✨ [FEAT] 주민등록번호로 age 계산 

src/main/java/com/carely/backend/dto/news/NewsCommentResponseDTO.java, src/main/java/com/carely/backend/dto/news/NewsResponseDTO.java
=> 🐛 [FIX] 모임 정보 응답 시 작성자 id 전달

src/main/java/com/carely/backend/controller/UserController.java, src/main/java/com/carely/backend/service/UserService.java
=> 🐛 [FIX] 요양보호사만 이미지 업로드

src/main/java/com/carely/backend/dto/document/ResponseDocumentDTO.java, src/main/java/com/carely/backend/service/DocumentIssuedService.java
=> 🐛 [FIX] partnerId 전달 

src/main/java/com/carely/backend/controller/GuestBookController.java, src/main/java/com/carely/backend/controller/docs/GuestBookAPI.java, src/main/java/com/carely/backend/domain/Group.java, src/main/java/com/carely/backend/domain/Volunteer.java, src/main/java/com/carely/backend/exception/GlobalHandleException.java, src/main/java/com/carely/backend/repository/GuestBookRepository.java, src/main/java/com/carely/backend/repository/JoinGroupRepository.java, src/main/java/com/carely/backend/repository/VolunteerRepository.java, src/main/java/com/carely/backend/service/GuestBookService.java, src/main/java/com/carely/backend/service/VolunteerService.java
- [📝 [DOCUMENT] swagger 추가](https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_43_BE/commit/86cd69152919bbcc042fca5a8dee8c0172a8407d)
- [📝 [DOCUMENT] swagger 추가](https://github.com/9oormthon-univ/2024_DANPOONG_TEAM_43_BE/commit/86cd69152919bbcc042fca5a8dee8c0172a8407d)
Resolved #121
=> 📝 [DOCUMENT] swagger 추가

src/main/java/com/carely/backend/controller/GuestBookController.java, src/main/java/com/carely/backend/controller/docs/GuestBookAPI.java
=> 🩹 [FIX] url 수정

src/main/java/com/carely/backend/dto/guestBook/ResponseGroupGuestbookDTO.java, src/main/java/com/carely/backend/service/GuestBookService.java
=> ✨ 방명록 조회 시 uesrId 전달 

src/main/java/com/carely/backend/dto/guestBook/ResponseGroupGuestbookDTO.java, src/main/java/com/carely/backend/service/GuestBookService.java
=> 🐛 [FIX] volunteer -> otherType

src/main/java/com/carely/backend/dto/user/MyPageDTO.java, src/main/java/com/carely/backend/service/UserService.java
- ✨ [FEAT] 함꼐한 추억 추가 - 프로필
- ✨ [FEAT] 함꼐한 추억 추가 - 프로필
Resolved #이슈번호
=> ✨ [FEAT] 함꼐한 추억 추가 - 프로필

src/main/java/com/carely/backend/controller/CertificateController.java, src/main/java/com/carely/backend/service/certificate/CertificateService.java
- 내✨ [FEAT] 자격증 발급 userId 없이 조회 구현
- 내용
Resolved #153
=> ✨ [FEAT] 자격증 발급 userId 없이 조회 구현

src/main/java/com/carely/backend/dto/group/GetGroupDTO.java, src/main/java/com/carely/backend/repository/GroupRepository.java, src/main/java/com/carely/backend/repository/JoinGroupRepository.java, src/main/java/com/carely/backend/service/GroupService.java
=> ✨ [FEAT] 그룹 가입 여부 전달, 가입하지 않은 그룹만 조회
